// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleManager.Data;

#nullable disable

namespace PeopleManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702033252_AddChecklistEvaluationRecordedAtAndComment")]
    partial class AddChecklistEvaluationRecordedAtAndComment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PeopleManager.Models.ActionItem", b =>
                {
                    b.Property<int>("ActionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletedInMeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletionNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedInMeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActionItemId");

                    b.HasIndex("CompletedInMeetingId");

                    b.HasIndex("CreatedInMeetingId");

                    b.HasIndex("PersonId", "IsComplete");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("PeopleManager.Models.ChecklistItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValueType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("PeopleManager.Models.ChecklistItemEvaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EvaluatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("EvaluationId");

                    b.HasIndex("ItemId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("PersonId", "ItemId", "EvaluatedDate");

                    b.ToTable("ChecklistItemEvaluations");
                });

            modelBuilder.Entity("PeopleManager.Models.GlowGrow", b =>
                {
                    b.Property<int>("GlowGrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CommunicatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("GlowGrowId");

                    b.HasIndex("PersonId");

                    b.ToTable("GlowsGrows");
                });

            modelBuilder.Entity("PeopleManager.Models.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MeetingId");

                    b.HasIndex("PersonId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("PeopleManager.Models.MeetingNote", b =>
                {
                    b.Property<int>("MeetingNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MeetingNoteId");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingNotes");
                });

            modelBuilder.Entity("PeopleManager.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludedFromShadowing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PeopleManager.Models.PersonEmploymentPeriod", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SeparationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeparationNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeparationReason")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeriodId");

                    b.HasIndex("PersonId", "SeparationDate");

                    b.ToTable("PersonEmploymentPeriods");
                });

            modelBuilder.Entity("PeopleManager.Models.PersonItemAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PersonId", "ItemId")
                        .IsUnique();

                    b.ToTable("PersonItemAssignments");
                });

            modelBuilder.Entity("PeopleManager.Models.PersonJobTitle", b =>
                {
                    b.Property<int>("PersonJobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonJobTitleId");

                    b.HasIndex("PersonId", "EffectiveDate");

                    b.ToTable("PersonJobTitles");
                });

            modelBuilder.Entity("PeopleManager.Models.PersonProjectAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ProjectTeamId");

                    b.HasIndex("PersonId", "RemovedDate");

                    b.ToTable("PersonProjectAssignments");
                });

            modelBuilder.Entity("PeopleManager.Models.ProjectTeam", b =>
                {
                    b.Property<int>("ProjectTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectTeamId");

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("PeopleManager.Models.ShadowSession", b =>
                {
                    b.Property<int>("ShadowSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservedPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Points")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShadowerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamObserved")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ShadowSessionId");

                    b.HasIndex("ObservedPersonId");

                    b.HasIndex("ShadowerId", "Date");

                    b.ToTable("ShadowSessions");
                });

            modelBuilder.Entity("PeopleManager.Models.ActionItem", b =>
                {
                    b.HasOne("PeopleManager.Models.Meeting", "CompletedInMeeting")
                        .WithMany()
                        .HasForeignKey("CompletedInMeetingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeopleManager.Models.Meeting", "CreatedInMeeting")
                        .WithMany("CreatedActionItems")
                        .HasForeignKey("CreatedInMeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeopleManager.Models.Person", "Person")
                        .WithMany("ActionItems")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompletedInMeeting");

                    b.Navigation("CreatedInMeeting");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PeopleManager.Models.ChecklistItemEvaluation", b =>
                {
                    b.HasOne("PeopleManager.Models.ChecklistItem", "Item")
                        .WithMany("Evaluations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeopleManager.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PeopleManager.Models.Person", "Person")
                        .WithMany("ChecklistEvaluations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Meeting");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PeopleManager.Models.GlowGrow", b =>
                {
                    b.HasOne("PeopleManager.Models.Person", "Person")
                        .WithMany("GlowsGrows")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PeopleManager.Models.Meeting", b =>
                {
                    b.HasOne("PeopleManager.Models.Person", "Person")
                        .WithMany("Meetings")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PeopleManager.Models.MeetingNote", b =>
                {
                    b.HasOne("PeopleManager.Models.Meeting", "Meeting")
                        .WithMany("Notes")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("PeopleManager.Models.PersonEmploymentPeriod", b =>
                {
                    b.HasOne("PeopleManager.Models.Person", "Person")
                        .WithMany("EmploymentPeriods")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PeopleManager.Models.PersonItemAssignment", b =>
                {
                    b.HasOne("PeopleManager.Models.ChecklistItem", "Item")
                        .WithMany("Assignments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeopleManager.Models.Person", "Person")
                        .WithMany("ItemAssignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PeopleManager.Models.PersonJobTitle", b =>
                {
                    b.HasOne("PeopleManager.Models.Person", "Person")
                        .WithMany("JobTitles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PeopleManager.Models.PersonProjectAssignment", b =>
                {
                    b.HasOne("PeopleManager.Models.Person", "Person")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeopleManager.Models.ProjectTeam", "ProjectTeam")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("ProjectTeam");
                });

            modelBuilder.Entity("PeopleManager.Models.ShadowSession", b =>
                {
                    b.HasOne("PeopleManager.Models.Person", "ObservedPerson")
                        .WithMany("ShadowSessionsAsObserved")
                        .HasForeignKey("ObservedPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeopleManager.Models.Person", "Shadower")
                        .WithMany("ShadowSessionsAsShadower")
                        .HasForeignKey("ShadowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObservedPerson");

                    b.Navigation("Shadower");
                });

            modelBuilder.Entity("PeopleManager.Models.ChecklistItem", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("PeopleManager.Models.Meeting", b =>
                {
                    b.Navigation("CreatedActionItems");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("PeopleManager.Models.Person", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("ChecklistEvaluations");

                    b.Navigation("EmploymentPeriods");

                    b.Navigation("GlowsGrows");

                    b.Navigation("ItemAssignments");

                    b.Navigation("JobTitles");

                    b.Navigation("Meetings");

                    b.Navigation("ProjectAssignments");

                    b.Navigation("ShadowSessionsAsObserved");

                    b.Navigation("ShadowSessionsAsShadower");
                });

            modelBuilder.Entity("PeopleManager.Models.ProjectTeam", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
